# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  UiPath Test Suite Team

steps:
- script: echo Hello, world!  
  displayName: 'Run a one-line script'

- script: |
    echo Hello test suite team
  displayName: 'Run a multi-line script'
- task: UiPathInstallPlatform@4
  inputs:
    cliVersion: 'WIN_23.10.8894.39673'
